run:
  deadline: 5m

linters:
  disable:
    - errcheck
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - containedctx
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  maintidx:
    under: 40
  misspell:
    locale: US
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 96
    tab-width: 1
  nlreturn:
    block-size: 5
  goimports:
    local-prefixes: github.com/vladopajic/go-actor-examples
  wsl:
    enforce-err-cuddling: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen      ## Function lenght is okay due to many tests cases
        - wrapcheck   ## No need to check wrapping errors in tests

    - path: _export_test\.go
      linters:
        - revive      ## Disabling linter because we intentionally want to use unexpored types in tests

      # Linters excluded from examples
    - path: example/*
      linters:
        - gomnd
